# Generated by Django 2.1.15 on 2021-12-26 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('TeamId', models.CharField(blank=True, max_length=255, primary_key=True, serialize=False)),
                ('OrganizationId', models.CharField(blank=True, max_length=255)),
                ('BusinessunitId', models.CharField(blank=True, max_length=255)),
                ('Name', models.CharField(blank=True, max_length=255)),
                ('Description', models.TextField(blank=True, null=True)),
                ('CreatedOn', models.DateTimeField(blank=True, null=True)),
                ('ModifiedOn', models.DateTimeField(blank=True, null=True)),
                ('createdBy', models.CharField(blank=True, max_length=255, null=True)),
                ('ModifiedBy', models.CharField(blank=True, max_length=255, null=True)),
                ('IsDefault', models.BooleanField(blank=True, max_length=255)),
                ('AdministratorId', models.CharField(blank=True, max_length=255)),
                ('QueueId', models.CharField(blank=True, max_length=255, null=True)),
                ('TeamType', models.IntegerField(blank=True)),
                ('TeamTemplateId', models.CharField(blank=True, max_length=255, null=True)),
                ('RegardingObjectTypeCode', models.IntegerField(blank=True, null=True)),
                ('Manager', models.CharField(blank=True, max_length=255, null=True)),
                ('SalesPurchaseManager', models.CharField(blank=True, max_length=255, null=True)),
                ('Id', models.IntegerField(null=True)),
                ('WegeDetailAccount', models.CharField(blank=True, max_length=255, null=True)),
                ('PoursantDetailAccount', models.CharField(blank=True, max_length=255, null=True)),
                ('Subsidiary', models.CharField(blank=True, max_length=255, null=True)),
                ('WegeFactorsDetailAccount', models.CharField(blank=True, max_length=255, null=True)),
                ('PoursantFactorsDetailAccount', models.CharField(blank=True, max_length=255, null=True)),
                ('UnitManager', models.CharField(blank=True, max_length=255, null=True)),
                ('TeamPercentage', models.DecimalField(blank=True, decimal_places=10, max_digits=23)),
                ('Goal', models.CharField(blank=True, max_length=255, null=True)),
                ('UserCount', models.IntegerField(blank=True, null=True)),
                ('NewTeamType', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
