# Generated by Django 2.1.15 on 2021-12-27 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0002_auto_20211226_1530'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Team',
        ),
    ]
