# Generated by Django 2.1.15 on 2021-12-27 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myapi', '0003_delete_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('teamid', models.CharField(db_column='TeamId', max_length=36)),
                ('organizationid', models.CharField(db_column='OrganizationId', max_length=36)),
                ('businessunitid', models.CharField(db_column='BusinessUnitId', max_length=36)),
                ('name', models.CharField(db_column='Name', max_length=160)),
                ('description', models.TextField(blank=True, db_column='Description', null=True)),
                ('createdon', models.DateTimeField(blank=True, db_column='CreatedOn', null=True)),
                ('modifiedon', models.DateTimeField(blank=True, db_column='ModifiedOn', null=True)),
                ('createdby', models.CharField(blank=True, db_column='CreatedBy', max_length=36, null=True)),
                ('modifiedby', models.CharField(blank=True, db_column='ModifiedBy', max_length=36, null=True)),
                ('isdefault', models.BooleanField(db_column='IsDefault')),
                ('administratorid', models.CharField(db_column='AdministratorId', max_length=36)),
                ('queueid', models.CharField(blank=True, db_column='QueueId', max_length=36, null=True)),
                ('teamtype', models.IntegerField(db_column='TeamType')),
                ('teamtemplateid', models.CharField(blank=True, db_column='TeamTemplateId', max_length=36, null=True)),
                ('regardingobjecttypecode', models.IntegerField(blank=True, db_column='RegardingObjectTypeCode', null=True)),
                ('manager', models.CharField(blank=True, db_column='Manager', max_length=36, null=True)),
                ('salespurchasemanager', models.CharField(blank=True, db_column='SalesPurchaseManager', max_length=36, null=True)),
                ('id', models.IntegerField(blank=True, db_column='Id', primary_key=True, serialize=False)),
                ('wegedetailaccount', models.CharField(blank=True, db_column='WegeDetailAccount', max_length=36, null=True)),
                ('poursantdetailaccount', models.CharField(blank=True, db_column='PoursantDetailAccount', max_length=36, null=True)),
                ('subsidiary', models.CharField(blank=True, db_column='Subsidiary', max_length=36, null=True)),
                ('wegefactorsdetailaccount', models.CharField(blank=True, db_column='WegeFactorsDetailAccount', max_length=36, null=True)),
                ('poursantfactorsdetailaccount', models.CharField(blank=True, db_column='PoursantFactorsDetailAccount', max_length=36, null=True)),
                ('unitmanager', models.CharField(blank=True, db_column='UnitManager', max_length=36, null=True)),
                ('teampercentage', models.DecimalField(blank=True, db_column='TeamPercentage', decimal_places=10, max_digits=23, null=True)),
                ('goal', models.CharField(blank=True, db_column='Goal', max_length=36, null=True)),
                ('usercount', models.IntegerField(blank=True, db_column='UserCount', null=True)),
                ('newteamtype', models.IntegerField(blank=True, db_column='NewTeamType', null=True)),
            ],
            options={
                'db_table': 'Team',
                'managed': False,
            },
        ),
    ]
